### ISSUE TITLE
Make wizard cache setter tz aware

### ISSUE THREAD

**Issue by Pringels** [django-recaptcha/django-recaptcha#123]
Ensure that wizard cache setter times are tz aware. (with UTC set as the zone)

See related comment:
https://github.com/praekelt/django-recaptcha/pull/122#discussion_r101215729

**Comment by thibaudcolas** [comment]
I see no comments on this for close to 7 years now. I’ll close this, if anyone feels like there is more work to do please open a new issue with more details.
