### ISSUE TITLE
Error Javascript Reference to JS Google File. Maybe Wait Page load?

### ISSUE THREAD

**Issue by Bernardoow** [django-recaptcha/django-recaptcha#138]
I always put js file before close body.

This lib é load before the js load file.

Can we use this code: `window.onload = function(){
    // code goes here
};` ? That wait the load page to do any thing with JS.

https://github.com/praekelt/django-recaptcha/blob/ef6e95f0e26dfceaeca0d791b45fc2efb0f6ba01/captcha/templates/captcha/widget_ajax.html#L7

**Comment by thibaudcolas** [comment]
I see no comments on this for close to 7 years now. I’ll close this, if anyone feels like there is more work to do please open a new issue with more details.
