### ISSUE TITLE
Captcha field shows "Incorrect, please try again" for any field error

### ISSUE THREAD

**Issue by adambyer** [django-recaptcha/django-recaptcha#139]
I'm using a captcha field on a form to create accounts. The captcha field always displays "Incorrect, please try again" when there are errors on other fields. For example, if the email address is invalid, the captcha field also displays an error. Is there a way to prevent this?

**Comment by niotech** [comment]
+1

**Comment by jarkow** [comment]
+1

**Comment by lirlocker** [comment]
+1

**Comment by belek** [comment]
I also got this error, but other fields are ok

**Comment by thibaudcolas** [comment]
I see no comments on this for close to 6 years now. I’ll close this, if anyone feels like there is more work to do please open a new issue with more details.
