### ISSUE TITLE
HTML5 Validation Errors

### ISSUE THREAD

**Issue by 9mido** [django-recaptcha/django-recaptcha#212]
Attribute required_score not allowed on element input at this point.

Attribute required not allowed on element input at this point.

Attribute required is only allowed when the input type is checkbox, date, datetime-local, email, file, month, number, password, radio, search, tel, text, time, url, or week.

The type attribute is unnecessary for JavaScript resources.

```html
<script src="https://www.google.com/recaptcha/api.js?render=KEY"></script>
<script type="text/javascript">
    grecaptcha.ready(function() {
        grecaptcha.execute('KEY', {action: 'form'})
        .then(function(token) {
            console.log("reCAPTCHA validated for 'data-widget-uuid=\"c66d1bce169e4cc2b90aece30a74629e\"'. Setting input value...")
            var element = document.querySelector('.g-recaptcha[data-widget-uuid="c66d1bce169e4cc2b90aece30a74629e"]');
            element.value = token;
        });
    });
</script>

<input class="g-recaptcha"
    type="hidden"
    name="captcha"
     required_score="None" data-sitekey="KEY" required id="id_captcha" data-widget-uuid="c66d1bce169e4cc2b90aece30a74629e" data-callback="onSubmit_c66d1bce169e4cc2b90aece30a74629e" data-size="normal"
>
```

**Comment by thibaudcolas** [comment]
I ran into the same thing and am happy to see this is already reported. In my case the `required` attribute is problematic because it’s on a `div`:

```html
<script type="text/javascript">
    // Submit function to be called, after reCAPTCHA was successful.
    var onSubmit_[...] = function(token) {
        console.log("reCAPTCHA validated for 'data-widget-uuid=\"[...]\"'")
    };
</script>

<div class="g-recaptcha"
     data-sitekey="[...]" required id="id_wagtailcaptcha" data-widget-uuid="[...]]" data-callback="onSubmit_[...]]" data-size="normal"

</div>
```

**Comment by rber474** [comment]
I faced same validation problems. For required attribute validation error I have override it with
```
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(EmailPostForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['captcha'].required = False
```

I will try to fix required_score attribute and PR it.

**Comment by Stormheg** [comment]
The issues reported here have recently been fixed in https://github.com/django-recaptcha/django-recaptcha/pull/330, https://github.com/django-recaptcha/django-recaptcha/pull/328 and https://github.com/django-recaptcha/django-recaptcha/pull/324 respectively

All fixes will be released in the next release 🙌 🚀
