### ISSUE TITLE
"This field is required" in development mode

### ISSUE THREAD

**Issue by axil** [django-recaptcha/django-recaptcha#215]
Like described in the docs I omitted RECAPTCHA_PRIVATE_KEY and RECAPTCHA_PUBLIC_KEY from settings.py and added SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error'].

I'm getting "This field is required" message because the captcha field is left empty in this scenario.

What's the intended way to deal with this?

**Comment by axil** [comment]
I've added PR #216 with the three character solution to this issue.

**Comment by thibaudcolas** [comment]
Closing in favour of #218, which seems to be the same scenario.
