### ISSUE TITLE
Add fa language

### ISSUE THREAD

**Issue by BamdadMeh** [django-recaptcha/django-recaptcha#285]
Hi
I'am Iranian and "fa" is my native language
I want to improve languages for this package,
So : 
language : fa
msgid "Error verifying reCAPTCHA, please try again."
msgstr "در بررسی یا تایید reCAPTCHA خطایی رخ داده است، لطفا دوباره تلاش کنید"

Thanks

**Comment by Stormheg** [comment]
Translation added via #326. Thanks!
