### ISSUE TITLE
Submitting a protected form using javascript breaks captcha

### ISSUE THREAD

**Issue by den1251** [django-recaptcha/django-recaptcha#359]
**Describe the bug**
When I add a js code which prevents form from submitting, executes a function and after that submits. The website returns (client side) `(Hidden field captcha) This field is required.`. Script part of that I use (the one that messes up the captcha) is written below

```
    document.getElementById("referat").addEventListener("submit", async function(e) {
            e.preventDefault();
            var hiddenInput = document.createElement("input");
            hiddenInput.type = "hidden";
            hiddenInput.name = "late_fingerprint";
            hiddenInput.id = "late_fingerprint";
            document.getElementById("referat").appendChild(hiddenInput);
            await generateFingerprint("late_fingerprint");
            console.log("Late Fingerprint Value: ", document.getElementById("late_fingerprint").value);
            this.submit();
        });

```

**To Reproduce**
Add to your js prevention of submission of a captcha protected form (wait for some function to complete) after that submit from the js

**Expected behavior**
Recaptcha will be alright with that

**Screenshots**
![image](https://github.com/user-attachments/assets/ba1fe679-e5cb-4877-b980-6edd02b43c62)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox

**Comment by den1251** [comment]
Adding `grecaptcha.execute()` in the js before it submits the form solves the issue

**Comment by Stormheg** [comment]
Hello @den1251 - glad to see you already found a workaround. For what is worth, this sounds like a duplicate of https://github.com/django-recaptcha/django-recaptcha/issues/348

This is something we broke and I believe should be fixed. Just not sure yet how. https://github.com/django-recaptcha/django-recaptcha/issues/348#issuecomment-1951933653
